//! Configuration Handling Module
//! 
//! **Config Module** (Module cấu hình - load/save/validate config YAML)
//! 
//! This module handles configuration file operations including:
//! - Loading config from YAML files
//! - Validating configuration
//! - Generating proxy-config.yaml for CLIProxyAPI

mod types;
mod loader;

pub use types::*;
pub use loader::*;

use anyhow::{Result, Context, bail};
use std::path::Path;
use tracing::{info, warn};

/// Validate a configuration file
/// **validate** (Xác thực - kiểm tra file config hợp lệ)
pub fn validate(config_path: &str) -> Result<()> {
    let path = Path::new(config_path);
    
    if !path.exists() {
        bail!("Configuration file not found: {}", config_path);
    }
    
    let config = load_config(config_path)
        .context("Failed to parse configuration file")?;
    
    // Validate required fields
    // **Validate** (Kiểm tra - xác nhận các trường bắt buộc)
    if config.port == 0 {
        warn!("Port is set to 0, will use default port 8317");
    }
    
    if config.port > 65535 {
        bail!("Invalid port number: {} (must be 1-65535)", config.port);
    }
    
    info!("✓ Configuration is valid");
    info!("  Port: {}", config.port);
    info!("  Debug: {}", config.debug);
    info!("  Logging to file: {}", config.logging_to_file);
    
    Ok(())
}

/// Show current configuration
/// **show** (Hiển thị - in config hiện tại)
pub fn show(config_path: &str) -> Result<()> {
    let path = Path::new(config_path);
    
    if !path.exists() {
        bail!("Configuration file not found: {}", config_path);
    }
    
    let content = std::fs::read_to_string(path)
        .context("Failed to read configuration file")?;
    
    println!("{}", content);
    
    Ok(())
}

/// Initialize a new configuration file
/// **init** (Khởi tạo - tạo file config mới)
pub fn init(config_path: &str, force: bool) -> Result<()> {
    let path = Path::new(config_path);
    
    if path.exists() && !force {
        bail!(
            "Configuration file already exists: {}\nUse --force to overwrite",
            config_path
        );
    }
    
    let default_config = AppConfig::default();
    let yaml = serde_yaml::to_string(&default_config)
        .context("Failed to serialize default configuration")?;
    
    // Add header comment
    // **Header** (Tiêu đề - thêm comment mô tả)
    let content = format!(
        "# ProxyPal Headless Configuration\n\
         # Generated by: proxypal config init\n\
         # Documentation: https://github.com/wollfoo/cli-all-api\n\n\
         {}", 
        yaml
    );
    
    std::fs::write(path, content)
        .context("Failed to write configuration file")?;
    
    info!("✓ Configuration file created: {}", config_path);
    
    Ok(())
}
